sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t limethecoder/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true limethecoder/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-central-1-766115077019"
    bucket_path: "docker-react"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on:
        branch: master