sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t limethecoder/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true limethecoder/docker-react npm run test